import images from './images';

export const products = [
  {
    id: 0,
    discount: 30,
    liked: false,
    productName: 'Coffee',
    auctionId: null,
    price: 700,
    minimumPrice: 9.9,
    originalPrice: 1000,
    image: images.coffee,
    time: '2d 14h 5m 11s',
    category: 'Electronic',
    description:
      "Coffee Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 1,
    discount: 30,
    liked: true,
    productName: 'Tea',
    auctionId: null,
    price: 500,
    minimumPrice: 10.9,
    originalPrice: 7000,
    image: images.perfume,
    time: '2d 14h 5m 11s',
    category: 'Tech',
    description:
      "Tea Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 2,
    discount: 30,
    liked: false,
    productName: 'Juice',
    auctionId: null,
    price: 300,
    minimumPrice: 11.9,
    originalPrice: 500,
    image: images.headphones,
    time: '2d 14h 5m 11s',
    category: 'Sports',
    description:
      "Juice Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 3,
    discount: 30,
    liked: true,
    productName: 'Biscuit',
    auctionId: null,
    price: 150,
    minimumPrice: 12.9,
    originalPrice: 300,
    image: images.coffee,
    time: '2d 14h 5m 11s',
    category: 'Food',
    description:
      "Biscuit Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 4,
    discount: 30,
    liked: false,
    productName: 'Slanty',
    auctionId: null,
    price: 75,
    minimumPrice: 13.9,
    originalPrice: 150,
    image: images.perfume,
    time: '2d 14h 5m 11s',
    category: 'Electronic',
    description:
      "Slanty Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 5,
    discount: 30,
    liked: true,
    productName: 'Chewing Gum',
    auctionId: null,
    price: 35,
    minimumPrice: 14.9,
    originalPrice: 75,
    image: images.headphones,
    time: '2d 14h 5m 11s',
    category: 'Tech',
    description:
      "Chewing Gum Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 6,
    discount: 30,
    liked: false,
    productName: 'Coffee',
    auctionId: '005',
    price: 700,
    minimumPrice: 9.9,
    originalPrice: 1000,
    image: images.coffee,
    time: '2d 14h 5m 11s',
    description:
      "Coffee Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 7,
    discount: 30,
    liked: true,
    productName: 'Tea',
    auctionId: '006',
    price: 500,
    minimumPrice: 10.9,
    originalPrice: 7000,
    image: images.perfume,
    time: '2d 14h 5m 11s',
    category: 'Food',
    description:
      "Tea Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 8,
    discount: 30,
    liked: false,
    productName: 'Juice',
    auctionId: '007',
    price: 300,
    minimumPrice: 11.9,
    originalPrice: 500,
    image: images.headphones,
    time: '2d 14h 5m 11s',
    category: 'Electronic',
    description:
      "Juice Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 9,
    discount: 30,
    liked: true,
    productName: 'Biscuit',
    auctionId: '008',
    price: 150,
    minimumPrice: 12.9,
    originalPrice: 300,
    image: images.coffee,
    time: '2d 14h 5m 11s',
    category: 'Tech',
    description:
      "Biscuit Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 10,
    discount: 30,
    liked: false,
    productName: 'Slanty',
    auctionId: '009',
    price: 75,
    minimumPrice: 13.9,
    originalPrice: 150,
    image: images.perfume,
    time: '2d 14h 5m 11s',
    category: 'Sports',
    description:
      "Slanty Queen Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
  {
    id: 11,
    discount: 30,
    liked: true,
    productName: 'Chewing Gum',
    auctionId: '010',
    price: 35,
    minimumPrice: 14.9,
    originalPrice: 75,
    image: images.headphones,
    time: '2d 14h 5m 11s',
    category: 'Food',
    description:
      "Chewing Gum Hip Hop Jewelry diamond cuban link chain 100% Real Solid Yellow gold of approximately 199.01 Grams weight and showcase natural 26.31 carats of prong setting cut diamond with FG/GH color & VS2/SI1/SI2/I1 clarity diamond. This mens chains available in 10k/14k/18k gold purity and yellow/rose/white gold. You'll get best price guarantee, Free us Shipping, 30 Days Return, Worldwide Shipping.",
  },
];

export const categories = [
  {
    id: 0,
    categoryName: 'All',
  },
  {
    id: 1,
    categoryName: 'Electronic',
  },
  {
    id: 2,
    categoryName: 'Tech',
  },
  {
    id: 3,
    categoryName: 'Sports',
  },
  {
    id: 4,
    categoryName: 'Food',
  },
];

export const analytics = [
  {
    id: 0,
    productName: 'Silver Bag Gucci',
    date: '19-08-2022',
    paid: '500.00',
  },
  {
    id: 1,
    productName: 'Silver Bag Gucci',
    date: '19-08-2022',
    paid: '500.00',
  },
  {
    id: 2,
    productName: 'Silver Bag Gucci',
    date: '19-08-2022',
    paid: '500.00',
  },
  {
    id: 3,
    productName: 'Silver Bag Gucci',
    date: '19-08-2022',
    paid: '500.00',
  },
  {
    id: 4,
    productName: 'Silver Bag Gucci',
    date: '19-08-2022',
    paid: '500.00',
  },
];
