export default Object.freeze({
  SPLASH: 'Splash',
  ON_BOARDING_ONE: 'OnBoardingOne',
  ON_BOARDING_TWO: 'OnBoardingTwo',
  REGISTER: 'Register',
  LOGIN: 'Login',
  HOME: 'Home',
  SEARCH: 'Search',
  CART: 'Cart',
  ANALYTICS: 'Analytics',
  LIKED: 'Liked',
  PRODUCTS: 'Products',
  BIDS: 'Bids',
  PRODUCT_DETAIL: 'ProductDetail',
  ACCOUNT: 'Account',
  UPLOAD_PRODUCT: 'UploadProduct',
  STRIPE: 'Stripe',
});
